In [1]:
import pandas as pd 
data=pd.read_csv('C:\\Users\\pc\\python-basics\\Example1_pandas.csv')
data

    ID       Name     Place  Gender   Age
0  101       Jaya    London  Female  23.0
1  102      Jeena   NewYork  Female   NaN
2  103      Elena    London  Female  22.0
3  104  Katherine   NewYork  Female  25.0
4  105      Damon  Virginia    Male  45.0
5  106     Bonnie   Georgia  Female   NaN
6  107       Joey   NewYork    Male  30.0
7  108      Hessa       NaN  Female  21.0
8  109       Ayan     Saudi    Male  29.0
9  110       Robb       NaN    Male   NaN

In [5]:
data.shape

(10, 5)

In [6]:
data.head(4)

    ID       Name    Place  Gender   Age
0  101       Jaya   London  Female  23.0
1  102      Jeena  NewYork  Female   NaN
2  103      Elena   London  Female  22.0
3  104  Katherine  NewYork  Female  25.0

In [7]:
data.tail(6)

    ID    Name     Place  Gender   Age
4  105   Damon  Virginia    Male  45.0
5  106  Bonnie   Georgia  Female   NaN
6  107    Joey   NewYork    Male  30.0
7  108   Hessa       NaN  Female  21.0
8  109    Ayan     Saudi    Male  29.0
9  110    Robb       NaN    Male   NaN

In [8]:
data.columns

Index(['ID', 'Name', 'Place', 'Gender', 'Age'], dtype='object')

In [10]:
data['Age']

0    23.0
1     NaN
2    22.0
3    25.0
4    45.0
5     NaN
6    30.0
7    21.0
8    29.0
9     NaN
Name: Age, dtype: float64

In [12]:
data[['Age','Name','ID']]

    Age       Name   ID
0  23.0       Jaya  101
1   NaN      Jeena  102
2  22.0      Elena  103
3  25.0  Katherine  104
4  45.0      Damon  105
5   NaN     Bonnie  106
6  30.0       Joey  107
7  21.0      Hessa  108
8  29.0       Ayan  109
9   NaN       Robb  110

In [16]:
new_data=data.drop('Age',axis=1)
new_data

    ID       Name     Place  Gender
0  101       Jaya    London  Female
1  102      Jeena   NewYork  Female
2  103      Elena    London  Female
3  104  Katherine   NewYork  Female
4  105      Damon  Virginia    Male
5  106     Bonnie   Georgia  Female
6  107       Joey   NewYork    Male
7  108      Hessa       NaN  Female
8  109       Ayan     Saudi    Male
9  110       Robb       NaN    Male

In [18]:
data.sort_values('Age')

    ID       Name     Place  Gender   Age
7  108      Hessa       NaN  Female  21.0
2  103      Elena    London  Female  22.0
0  101       Jaya    London  Female  23.0
3  104  Katherine   NewYork  Female  25.0
8  109       Ayan     Saudi    Male  29.0
6  107       Joey   NewYork    Male  30.0
4  105      Damon  Virginia    Male  45.0
1  102      Jeena   NewYork  Female   NaN
5  106     Bonnie   Georgia  Female   NaN
9  110       Robb       NaN    Male   NaN

In [19]:
data.sort_values('Name')

    ID       Name     Place  Gender   Age
8  109       Ayan     Saudi    Male  29.0
5  106     Bonnie   Georgia  Female   NaN
4  105      Damon  Virginia    Male  45.0
2  103      Elena    London  Female  22.0
7  108      Hessa       NaN  Female  21.0
0  101       Jaya    London  Female  23.0
1  102      Jeena   NewYork  Female   NaN
6  107       Joey   NewYork    Male  30.0
3  104  Katherine   NewYork  Female  25.0
9  110       Robb       NaN    Male   NaN

In [20]:
data.index

RangeIndex(start=0, stop=10, step=1)

In [25]:
data_index=data.set_index('ID')
data_index

          Name     Place  Gender   Age
ID
101       Jaya    London  Female  23.0
102      Jeena   NewYork  Female   NaN
103      Elena    London  Female  22.0
104  Katherine   NewYork  Female  25.0
105      Damon  Virginia    Male  45.0
106     Bonnie   Georgia  Female   NaN
107       Joey   NewYork    Male  30.0
108      Hessa       NaN  Female  21.0
109       Ayan     Saudi    Male  29.0
110       Robb       NaN    Male   NaN

In [26]:
data.loc[4]

ID             105
Name         Damon
Place     Virginia
Gender        Male
Age           45.0
Name: 4, dtype: object

In [35]:
new=data.set_index('Name')
new

            ID     Place  Gender   Age
Name
Jaya       101    London  Female  23.0
Jeena      102   NewYork  Female   NaN
Elena      103    London  Female  22.0
Katherine  104   NewYork  Female  25.0
Damon      105  Virginia    Male  45.0
Bonnie     106   Georgia  Female   NaN
Joey       107   NewYork    Male  30.0
Hessa      108       NaN  Female  21.0
Ayan       109     Saudi    Male  29.0
Robb       110       NaN    Male   NaN

In [36]:
new.loc['Ayan']

ID          109
Place     Saudi
Gender     Male
Age        29.0
Name: Ayan, dtype: object

In [37]:
data.iloc[3]

ID              104
Name      Katherine
Place       NewYork
Gender       Female
Age            25.0
Name: 3, dtype: object

In [38]:
data.copy()

    ID       Name     Place  Gender   Age
0  101       Jaya    London  Female  23.0
1  102      Jeena   NewYork  Female   NaN
2  103      Elena    London  Female  22.0
3  104  Katherine   NewYork  Female  25.0
4  105      Damon  Virginia    Male  45.0
5  106     Bonnie   Georgia  Female   NaN
6  107       Joey   NewYork    Male  30.0
7  108      Hessa       NaN  Female  21.0
8  109       Ayan     Saudi    Male  29.0
9  110       Robb       NaN    Male   NaN

In [40]:
ds=data.drop('Age',axis=1)
ds

    ID       Name     Place  Gender
0  101       Jaya    London  Female
1  102      Jeena   NewYork  Female
2  103      Elena    London  Female
3  104  Katherine   NewYork  Female
4  105      Damon  Virginia    Male
5  106     Bonnie   Georgia  Female
6  107       Joey   NewYork    Male
7  108      Hessa       NaN  Female
8  109       Ayan     Saudi    Male
9  110       Robb       NaN    Male

In [43]:
data.Place.unique()

array(['London', 'NewYork', 'Virginia', 'Georgia', nan, 'Saudi'],
      dtype=object)

In [45]:
data.Place.value_counts

<bound method IndexOpsMixin.value_counts of 0      London
1     NewYork
2      London
3     NewYork
4    Virginia
5     Georgia
6     NewYork
7         NaN
8       Saudi
9         NaN
Name: Place, dtype: object>

In [46]:
for i in data:
    print(i)

ID
Name
Place
Gender
Age

In [47]:
for columns,values in data.items():
    print(columns)
    print(values)

ID
0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
Name: ID, dtype: int64
Name
0         Jaya
1        Jeena
2        Elena
3    Katherine
4        Damon
5       Bonnie
6         Joey
7        Hessa
8         Ayan
9         Robb
Name: Name, dtype: object
Place
0      London
1     NewYork
2      London
3     NewYork
4    Virginia
5     Georgia
6     NewYork
7         NaN
8       Saudi
9         NaN
Name: Place, dtype: object
Gender
0    Female
1    Female
2    Female
3    Female
4      Male
5    Female
6      Male
7    Female
8      Male
9      Male
Name: Gender, dtype: object
Age
0    23.0
1     NaN
2    22.0
3    25.0
4    45.0
5     NaN
6    30.0
7    21.0
8    29.0
9     NaN
Name: Age, dtype: float64

In [49]:
for index,row in data.iterrows():
    print('row:',index)
    print(row)

row: 0
ID           101
Name        Jaya
Place     London
Gender    Female
Age         23.0
Name: 0, dtype: object
row: 1
ID            102
Name        Jeena
Place     NewYork
Gender     Female
Age           NaN
Name: 1, dtype: object
row: 2
ID           103
Name       Elena
Place     London
Gender    Female
Age         22.0
Name: 2, dtype: object
row: 3
ID              104
Name      Katherine
Place       NewYork
Gender       Female
Age            25.0
Name: 3, dtype: object
row: 4
ID             105
Name         Damon
Place     Virginia
Gender        Male
Age           45.0
Name: 4, dtype: object
row: 5
ID            106
Name       Bonnie
Place     Georgia
Gender     Female
Age           NaN
Name: 5, dtype: object
row: 6
ID            107
Name         Joey
Place     NewYork
Gender       Male
Age          30.0
Name: 6, dtype: object
row: 7
ID           108
Name       Hessa
Place        NaN
Gender    Female
Age         21.0
Name: 7, dtype: object
row: 8
ID          109
Name       Ayan
Place     Saudi
Gender     Male
Age        29.0
Name: 8, dtype: object
row: 9
ID         110
Name      Robb
Place      NaN
Gender    Male
Age        NaN
Name: 9, dtype: object

In [50]:
data[1:4]

    ID       Name    Place  Gender   Age
1  102      Jeena  NewYork  Female   NaN
2  103      Elena   London  Female  22.0
3  104  Katherine  NewYork  Female  25.0

In [51]:
data[1:4:2]

    ID       Name    Place  Gender   Age
1  102      Jeena  NewYork  Female   NaN
3  104  Katherine  NewYork  Female  25.0

In [53]:
data[['Name','Place']][1:4]

        Name    Place
1      Jeena  NewYork
2      Elena   London
3  Katherine  NewYork

In [54]:
data.copy()

    ID       Name     Place  Gender   Age
0  101       Jaya    London  Female  23.0
1  102      Jeena   NewYork  Female   NaN
2  103      Elena    London  Female  22.0
3  104  Katherine   NewYork  Female  25.0
4  105      Damon  Virginia    Male  45.0
5  106     Bonnie   Georgia  Female   NaN
6  107       Joey   NewYork    Male  30.0
7  108      Hessa       NaN  Female  21.0
8  109       Ayan     Saudi    Male  29.0
9  110       Robb       NaN    Male   NaN

In [58]:
data.Age.max()

45.0

In [59]:
data.Age.min()

21.0

In [60]:
data.Age.sum()

195.0

In [61]:
data.Age.mean()

27.857142857142858

In [62]:
data.Age.std()

8.295150620062532

In [63]:
data.describe()

              ID        Age
count   10.00000   7.000000
mean   105.50000  27.857143
std      3.02765   8.295151
min    101.00000  21.000000
25%    103.25000  22.500000
50%    105.50000  25.000000
75%    107.75000  29.500000
max    110.00000  45.000000

In [66]:
data[data['Age']>30]

    ID   Name     Place Gender   Age
4  105  Damon  Virginia   Male  45.0

In [68]:
data['Name'][data.Age==data.Age.min()]

7    Hessa
Name: Name, dtype: object

In [69]:
data.copy()

    ID       Name     Place  Gender   Age
0  101       Jaya    London  Female  23.0
1  102      Jeena   NewYork  Female   NaN
2  103      Elena    London  Female  22.0
3  104  Katherine   NewYork  Female  25.0
4  105      Damon  Virginia    Male  45.0
5  106     Bonnie   Georgia  Female   NaN
6  107       Joey   NewYork    Male  30.0
7  108      Hessa       NaN  Female  21.0
8  109       Ayan     Saudi    Male  29.0
9  110       Robb       NaN    Male   NaN

In [74]:
data.isna()

      ID   Name  Place  Gender    Age
0  False  False  False   False  False
1  False  False  False   False   True
2  False  False  False   False  False
3  False  False  False   False  False
4  False  False  False   False  False
5  False  False  False   False   True
6  False  False  False   False  False
7  False  False   True   False  False
8  False  False  False   False  False
9  False  False   True   False   True

In [76]:
data.isna().sum()

ID        0
Name      0
Place     2
Gender    0
Age       3
dtype: int64

In [77]:
new_data=data.fillna(0)
new_data

    ID       Name     Place  Gender   Age
0  101       Jaya    London  Female  23.0
1  102      Jeena   NewYork  Female   0.0
2  103      Elena    London  Female  22.0
3  104  Katherine   NewYork  Female  25.0
4  105      Damon  Virginia    Male  45.0
5  106     Bonnie   Georgia  Female   0.0
6  107       Joey   NewYork    Male  30.0
7  108      Hessa         0  Female  21.0
8  109       Ayan     Saudi    Male  29.0
9  110       Robb         0    Male   0.0

In [78]:
avrg=data['Age'].mean()
data.fillna(avrg)

    ID       Name      Place  Gender        Age
0  101       Jaya     London  Female  23.000000
1  102      Jeena    NewYork  Female  27.857143
2  103      Elena     London  Female  22.000000
3  104  Katherine    NewYork  Female  25.000000
4  105      Damon   Virginia    Male  45.000000
5  106     Bonnie    Georgia  Female  27.857143
6  107       Joey    NewYork    Male  30.000000
7  108      Hessa  27.857143  Female  21.000000
8  109       Ayan      Saudi    Male  29.000000
9  110       Robb  27.857143    Male  27.857143

In [79]:
data.fillna(method='ffill')

C:\Users\pc\AppData\Local\Temp\ipykernel_3396\1844443866.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')

    ID       Name     Place  Gender   Age
0  101       Jaya    London  Female  23.0
1  102      Jeena   NewYork  Female  23.0
2  103      Elena    London  Female  22.0
3  104  Katherine   NewYork  Female  25.0
4  105      Damon  Virginia    Male  45.0
5  106     Bonnie   Georgia  Female  45.0
6  107       Joey   NewYork    Male  30.0
7  108      Hessa   NewYork  Female  21.0
8  109       Ayan     Saudi    Male  29.0
9  110       Robb     Saudi    Male  29.0

In [80]:
data.fillna(method='bfill')

C:\Users\pc\AppData\Local\Temp\ipykernel_3396\1397359497.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')

    ID       Name     Place  Gender   Age
0  101       Jaya    London  Female  23.0
1  102      Jeena   NewYork  Female  22.0
2  103      Elena    London  Female  22.0
3  104  Katherine   NewYork  Female  25.0
4  105      Damon  Virginia    Male  45.0
5  106     Bonnie   Georgia  Female  30.0
6  107       Joey   NewYork    Male  30.0
7  108      Hessa     Saudi  Female  21.0
8  109       Ayan     Saudi    Male  29.0
9  110       Robb       NaN    Male   NaN

In [81]:
data.bfill()

    ID       Name     Place  Gender   Age
0  101       Jaya    London  Female  23.0
1  102      Jeena   NewYork  Female  22.0
2  103      Elena    London  Female  22.0
3  104  Katherine   NewYork  Female  25.0
4  105      Damon  Virginia    Male  45.0
5  106     Bonnie   Georgia  Female  30.0
6  107       Joey   NewYork    Male  30.0
7  108      Hessa     Saudi  Female  21.0
8  109       Ayan     Saudi    Male  29.0
9  110       Robb       NaN    Male   NaN

In [82]:
data.interpolate()

C:\Users\pc\AppData\Local\Temp\ipykernel_3396\982976692.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  data.interpolate()

    ID       Name     Place  Gender   Age
0  101       Jaya    London  Female  23.0
1  102      Jeena   NewYork  Female  22.5
2  103      Elena    London  Female  22.0
3  104  Katherine   NewYork  Female  25.0
4  105      Damon  Virginia    Male  45.0
5  106     Bonnie   Georgia  Female  37.5
6  107       Joey   NewYork    Male  30.0
7  108      Hessa       NaN  Female  21.0
8  109       Ayan     Saudi    Male  29.0
9  110       Robb       NaN    Male  29.0

In [83]:
data.dropna()

    ID       Name     Place  Gender   Age
0  101       Jaya    London  Female  23.0
2  103      Elena    London  Female  22.0
3  104  Katherine   NewYork  Female  25.0
4  105      Damon  Virginia    Male  45.0
6  107       Joey   NewYork    Male  30.0
8  109       Ayan     Saudi    Male  29.0

In [85]:
data.dropna(how='all')

    ID       Name     Place  Gender   Age
0  101       Jaya    London  Female  23.0
1  102      Jeena   NewYork  Female   NaN
2  103      Elena    London  Female  22.0
3  104  Katherine   NewYork  Female  25.0
4  105      Damon  Virginia    Male  45.0
5  106     Bonnie   Georgia  Female   NaN
6  107       Joey   NewYork    Male  30.0
7  108      Hessa       NaN  Female  21.0
8  109       Ayan     Saudi    Male  29.0
9  110       Robb       NaN    Male   NaN

In [86]:
data.dropna(how='any')

    ID       Name     Place  Gender   Age
0  101       Jaya    London  Female  23.0
2  103      Elena    London  Female  22.0
3  104  Katherine   NewYork  Female  25.0
4  105      Damon  Virginia    Male  45.0
6  107       Joey   NewYork    Male  30.0
8  109       Ayan     Saudi    Male  29.0