In [ ]:
#pip install pandas
#!pip install pandas(to install pandas)
import pandas as pd

In [ ]:
print(pd.__version__)#to check the version pandas

2.3.3

In [ ]:
import numpy as np

PANDAS SERIES:

In [ ]:
#series:homogeneous and one diamensional (same type of elemnts)
#dataframe:hetrogeneous and two diamensional(differnt)

In [9]:

series_data=np.array([1,2,3,4,5])
pd.Series(series_data)

0    1
1    2
2    3
3    4
4    5
dtype: int64

DATA FRAME USING PYTHON DICTIONARY:

In [15]:
data={'Id':[101,102,103,104,105],'Name':['sam','alan','jessy','kate','hardin'],
'age':[15,16,17,18,15],'marks':[49,39,44,45,42]}
data

{'Id': [101, 102, 103, 104, 105],
 'Name': ['sam', 'alan', 'jessy', 'kate', 'hardin'],
 'age': [15, 16, 17, 18, 15],
 'marks': [49, 39, 44, 45, 42]}

In [16]:
dataframe1=pd.DataFrame(data)
dataframe1

    Id    Name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

DATA TYPE USING PYTHON TUPLE LIST:

In [17]:
data_tup=[(101,"sam",15,49),
          (102,"alan",16,39),
          (103,"jessy",17,44),
          (104,"kate",18,45),
          (105,"hardin",15,42)]
dataframe=pd.DataFrame(data_tup,columns=['id','name','age','marks'])
dataframe

    id    name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

DATAFRAME USING LIST OF DICTIONARIES:

In [19]:
data_list=[{'id':101,'Name':'sam','age':15,'marks':49},
           {'id':102,'Name':'alan','age':16,'marks':39},
           {'id':103,'Name':'jessy','age':17,'marks':44},
           {'id':104,'Name':'kate','age':18,'marks':45},
           {'id':105,'Name':'hardin','age':15,'marks':42}]
dataframe3=pd.DataFrame(data_list)
dataframe3

    id    Name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

READING A CSV FILE:

In [23]:
data=pd.read_csv('C:\\Users\\pc3\\python-basics\\weather_data_pandas (5).csv')#comma seperated values
data

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain
5  01-06-2017           31          2  Sunny

SKIP UNNECESSERY HEADERS AND ADD NEW HEADERS WHILE READING A CSV FILE: