In [ ]:
#pip install pandas
#!pip install pandas(to install pandas)
import pandas as pd

In [ ]:
print(pd.__version__)#to check the version pandas

2.3.3

In [ ]:
import numpy as np

PANDAS SERIES:

In [ ]:
#series:homogeneous and one diamensional (same type of elemnts)
#dataframe:hetrogeneous and two diamensional(differnt)

In [9]:

series_data=np.array([1,2,3,4,5])
pd.Series(series_data)

0    1
1    2
2    3
3    4
4    5
dtype: int64

DATA FRAME USING PYTHON DICTIONARY:

In [15]:
data={'Id':[101,102,103,104,105],'Name':['sam','alan','jessy','kate','hardin'],
'age':[15,16,17,18,15],'marks':[49,39,44,45,42]}
data

{'Id': [101, 102, 103, 104, 105],
 'Name': ['sam', 'alan', 'jessy', 'kate', 'hardin'],
 'age': [15, 16, 17, 18, 15],
 'marks': [49, 39, 44, 45, 42]}

In [16]:
dataframe1=pd.DataFrame(data)
dataframe1

    Id    Name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

DATA TYPE USING PYTHON TUPLE LIST:

In [17]:
data_tup=[(101,"sam",15,49),
          (102,"alan",16,39),
          (103,"jessy",17,44),
          (104,"kate",18,45),
          (105,"hardin",15,42)]
dataframe=pd.DataFrame(data_tup,columns=['id','name','age','marks'])
dataframe

    id    name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

DATAFRAME USING LIST OF DICTIONARIES:

In [19]:
data_list=[{'id':101,'Name':'sam','age':15,'marks':49},
           {'id':102,'Name':'alan','age':16,'marks':39},
           {'id':103,'Name':'jessy','age':17,'marks':44},
           {'id':104,'Name':'kate','age':18,'marks':45},
           {'id':105,'Name':'hardin','age':15,'marks':42}]
dataframe3=pd.DataFrame(data_list)
dataframe3

    id    Name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

READING A CSV FILE:

In [23]:
data=pd.read_csv('C:\\Users\\pc3\\python-basics\\weather_data_pandas (5).csv')#comma seperated values
data

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain
5  01-06-2017           31          2  Sunny

SKIP UNNECESSERY HEADERS AND ADD NEW HEADERS WHILE READING A CSV FILE:

In [4]:

data=pd.read_csv('C:\\Users\\pc3\\python-basics\\stock_data_pandas.csv')
data

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3     RIL  not available       50  1023  mukesh ambani
4    TATA             -1       -1  n.a.     ratan tata

In [5]:
#SKIPROWS:-skip the specified number of rows from the begining including the header row
data1=pd.read_csv('C:\\Users\\pc3\\python-basics\\stock_data_pandas.csv',skiprows=2)
data1

    WMT           4.61  484    65           n.a.
0  MSFT             -1   85    64     bill gates
1   RIL  not available   50  1023  mukesh ambani
2  TATA             -1   -1  n.a.     ratan tata

In [ ]:
#set the specified rows as the header discarding the remaining row of the data frame:
data2=pd.read_csv('C:\\Users\\pc3\\python-basics\\stock_data_pandas.csv',header=3)# will ser row 3 as header
data2

   MSFT             -1  85    64     bill gates
0   RIL  not available  50  1023  mukesh ambani
1  TATA             -1  -1  n.a.     ratan tata

In [ ]:
#make the header a new record:
d=pd.read_csv('C:\\Users\\pc3\\python-basics\\stock_data_pandas.csv',header=None)#header will be shown as new row and by default index no will be given
d

         0              1        2      3              4
0  tickers            eps  revenue  price         people
1    GOOGL          27.82       87    845     larry page
2      WMT           4.61      484     65           n.a.
3     MSFT             -1       85     64     bill gates
4      RIL  not available       50   1023  mukesh ambani
5     TATA             -1       -1   n.a.     ratan tata

In [9]:
#sets new names for the column:
data3=pd.read_csv('C:\\Users\\pc3\\python-basics\\stock_data_pandas.csv',header=None,names=["a","b","c","d","e"])
data3

         a              b        c      d              e
0  tickers            eps  revenue  price         people
1    GOOGL          27.82       87    845     larry page
2      WMT           4.61      484     65           n.a.
3     MSFT             -1       85     64     bill gates
4      RIL  not available       50   1023  mukesh ambani
5     TATA             -1       -1   n.a.     ratan tata

In [ ]:
#select only the first nrows from the data frames:
data4=pd.read_csv('C:\\Users\\pc3\\python-basics\\stock_data_pandas.csv',nrows=3)
data4 #will show first 3 rows only

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.
2    MSFT  -1.00       85     64  bill gates

In [12]:
#sets specific values from the dataframesas nul values:
#NaN-not a number (missing values)
data5=pd.read_csv('C:\\Users\\pc3\\python-basics\\stock_data_pandas.csv',na_values=['n.a.','not available'])
data5

  tickers    eps  revenue   price         people
0   GOOGL  27.82       87   845.0     larry page
1     WMT   4.61      484    65.0            NaN
2    MSFT  -1.00       85    64.0     bill gates
3     RIL    NaN       50  1023.0  mukesh ambani
4    TATA  -1.00       -1     NaN     ratan tata

In [14]:
data6=pd.read_csv('C:\\Users\\pc3\\python-basics\\stock_data_pandas.csv',na_values={'eps':['not available',-1],
                                                                                    'revenue':['n.a. ',-1,"-1"],'price':['n.a.',-1],
                                                                                      'people':['n.a','not available',-1]})
data6

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0           n.a.
2    MSFT    NaN     85.0    64.0     bill gates
3     RIL    NaN     50.0  1023.0  mukesh ambani
4    TATA    NaN      NaN     NaN     ratan tata

BASIC

In [5]:
import pandas as pd
emp={'Id':[101,102,103,104,105],'Name':['sam','alan','jessy','kate','hardin'],
'age':[15,16,17,18,15],'marks':[49,39,44,45,42]}
df=pd.DataFrame(emp)
df

    Id    Name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

In [6]:
#get shape og the dataframe
df.shape

(5, 4)

In [7]:
#display the 5 rows of dataframe:
df.head()

    Id    Name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

In [8]:
#return the specific number of records from the begining:
df.head(3)

    Id   Name  age  marks
0  101    sam   15     49
1  102   alan   16     39
2  103  jessy   17     44

In [19]:
#return last 5 rows
df.tail()

    Id    Name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

In [9]:
df.tail(2)

    Id    Name  age  marks
3  104    kate   18     45
4  105  hardin   15     42

In [10]:
#get the names of columns 
df.columns

Index(['Id', 'Name', 'age', 'marks'], dtype='object')

In [11]:
#accessing a specific column
df.age

0    15
1    16
2    17
3    18
4    15
Name: age, dtype: int64

In [12]:
df['age']

0    15
1    16
2    17
3    18
4    15
Name: age, dtype: int64

In [13]:
#accessing multiple column:
df[['Id','Name','age']]

    Id    Name  age
0  101     sam   15
1  102    alan   16
2  103   jessy   17
3  104    kate   18
4  105  hardin   15

In [15]:
#adding new column to dataframe
new_data=df.copy()
address=["delhi","lucknow","patna","delhi","delhi"]
new_data['Address']=address
new_data

    Id    Name  age  marks  Address
0  101     sam   15     49    delhi
1  102    alan   16     39  lucknow
2  103   jessy   17     44    patna
3  104    kate   18     45    delhi
4  105  hardin   15     42    delhi

In [16]:
#deleting a specific column 
new_data=new_data.drop('age',axis=1)
new_data

    Id    Name  marks  Address
0  101     sam     49    delhi
1  102    alan     39  lucknow
2  103   jessy     44    patna
3  104    kate     45    delhi
4  105  hardin     42    delhi

In [17]:
df.sort_values('age')#default sorting in ascending

    Id    Name  age  marks
0  101     sam   15     49
4  105  hardin   15     42
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45

In [ ]:
df.sort_values('age',ascending=False)#in descending order

    Id    Name  age  marks
3  104    kate   18     45
2  103   jessy   17     44
1  102    alan   16     39
0  101     sam   15     49
4  105  hardin   15     42

In [20]:
df.sort_values('Name')

    Id    Name  age  marks
1  102    alan   16     39
4  105  hardin   15     42
2  103   jessy   17     44
3  104    kate   18     45
0  101     sam   15     49

In [22]:
new_data.sort_values('Address',ascending=False)

    Id    Name  marks  Address
2  103   jessy     44    patna
1  102    alan     39  lucknow
0  101     sam     49    delhi
3  104    kate     45    delhi
4  105  hardin     42    delhi

In [23]:
#view the index assigned to th dataframe
df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
#changing index to some other column name
data_index=df.set_index('Id') #change the index as id  
data_index

       Name  age  marks
Id
101     sam   15     49
102    alan   16     39
103   jessy   17     44
104    kate   18     45
105  hardin   15     42

In [27]:
#resetting index to previous one
data_index=data_index.reset_index()
data_index

    Id    Name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

In [ ]:
#loc[location]#get values in index 3
df.loc[3]

Id        104
Name     kate
age        18
marks      45
Name: 3, dtype: object

In [29]:
df.loc[df.Name=="kate"]#another way to get values using names

    Id  Name  age  marks
3  104  kate   18     45

In [ ]:
dat=df.set_index('Name')#will set name as index
dat

         Id  age  marks
Name
sam     101   15     49
alan    102   16     39
jessy   103   17     44
kate    104   18     45
hardin  105   15     42

In [ ]:
dat.loc['hardin']#aftermaking name as index cam access using names

Id       105
age       15
marks     42
Name: hardin, dtype: int64

In [32]:
#iloc-pass only integer values
df.iloc[2]

Id         103
Name     jessy
age         17
marks       44
Name: 2, dtype: object

In [ ]:
dat.iloc[[0,3,4]]#accessing multiple values

         Id  age  marks
Name
sam     101   15     49
kate    104   18     45
hardin  105   15     42

In [34]:
#dtypes
df.dtypes

Id        int64
Name     object
age       int64
marks     int64
dtype: object

In [58]:
data=pd.read_csv('C:\\Users\\pc\\python-basics\\weather_data_pandas (5).csv')
data

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain
5  01-06-2017           31          2  Sunny

In [59]:
df.shape

(5, 4)

In [60]:
data=data.drop('event',axis=1)
data

          day  temperature  windspeed
0  01-01-2017           32          6
1  01-02-2017           35          7
2  01-03-2017           28          2
3  01-04-2017           24          7
4  01-05-2017           32          4
5  01-06-2017           31          2

In [61]:
data.sort_values('day')

          day  temperature  windspeed
0  01-01-2017           32          6
1  01-02-2017           35          7
2  01-03-2017           28          2
3  01-04-2017           24          7
4  01-05-2017           32          4
5  01-06-2017           31          2

In [62]:
data.sort_values('day',ascending=False)

          day  temperature  windspeed
5  01-06-2017           31          2
4  01-05-2017           32          4
3  01-04-2017           24          7
2  01-03-2017           28          2
1  01-02-2017           35          7
0  01-01-2017           32          6

In [63]:
data.sort_values('windspeed')

          day  temperature  windspeed
2  01-03-2017           28          2
5  01-06-2017           31          2
4  01-05-2017           32          4
0  01-01-2017           32          6
1  01-02-2017           35          7
3  01-04-2017           24          7

In [64]:
data.index

RangeIndex(start=0, stop=6, step=1)

In [65]:
ds=data.set_index('day')
ds

            temperature  windspeed
day
01-01-2017           32          6
01-02-2017           35          7
01-03-2017           28          2
01-04-2017           24          7
01-05-2017           32          4
01-06-2017           31          2

In [66]:
data.loc[2]

day            01-03-2017
temperature            28
windspeed               2
Name: 2, dtype: object

In [67]:
data.loc[data.windspeed==6]

          day  temperature  windspeed
0  01-01-2017           32          6

In [68]:
data.iloc[1]

day            01-02-2017
temperature            35
windspeed               7
Name: 1, dtype: object

In [70]:
data.iloc[[0,1,4]]

          day  temperature  windspeed
0  01-01-2017           32          6
1  01-02-2017           35          7
4  01-05-2017           32          4

In [71]:
data.dtypes

day            object
temperature     int64
windspeed       int64
dtype: object

In [ ]:
data.windspeed.unique()#get unique values from windspeed

array([6, 7, 2, 4], dtype=int64)

In [ ]:
data['windspeed'].unique()#another way to get unique values

array([6, 7, 2, 4], dtype=int64)

In [ ]:
data.windspeed.value_counts()#count how many times a values came

windspeed
7    2
2    2
6    1
4    1
Name: count, dtype: int64

In [ ]:

data2=pd.read_csv('C:\\Users\\pc\\python-basics\\stock_data_pandas.csv')
data2

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3     RIL  not available       50  1023  mukesh ambani
4    TATA             -1       -1  n.a.     ratan tata

In [79]:
#iterating over pandas
for i in data2:
    print(i)

tickers
eps
revenue
price
people

In [80]:
#getting column and values
for columns,values in data2.items():
    print(columns)
    print(values)

tickers
0    GOOGL
1      WMT
2     MSFT
3      RIL
4     TATA
Name: tickers, dtype: object
eps
0            27.82
1             4.61
2               -1
3    not available
4               -1
Name: eps, dtype: object
revenue
0     87
1    484
2     85
3     50
4     -1
Name: revenue, dtype: int64
price
0     845
1      65
2      64
3    1023
4    n.a.
Name: price, dtype: object
people
0       larry page
1             n.a.
2       bill gates
3    mukesh ambani
4       ratan tata
Name: people, dtype: object

In [81]:
#iterating through rows and its values 
for index,row in data2.iterrows():
    print('row:',index)
    print(row)

row: 0
tickers         GOOGL
eps             27.82
revenue            87
price             845
people     larry page
Name: 0, dtype: object
row: 1
tickers     WMT
eps        4.61
revenue     484
price        65
people     n.a.
Name: 1, dtype: object
row: 2
tickers          MSFT
eps                -1
revenue            85
price              64
people     bill gates
Name: 2, dtype: object
row: 3
tickers              RIL
eps        not available
revenue               50
price               1023
people     mukesh ambani
Name: 3, dtype: object
row: 4
tickers          TATA
eps                -1
revenue            -1
price            n.a.
people     ratan tata
Name: 4, dtype: object

In [82]:
#slicing:
data2[1:3]

  tickers   eps  revenue price      people
1     WMT  4.61      484    65        n.a.
2    MSFT    -1       85    64  bill gates

In [83]:
data2[:]

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3     RIL  not available       50  1023  mukesh ambani
4    TATA             -1       -1  n.a.     ratan tata

In [84]:
data2[['tickers','eps']][1:3]

  tickers   eps
1     WMT  4.61
2    MSFT    -1

In [89]:
list=[{'id':101,'Name':'sam','age':15,'marks':49},
           {'id':102,'Name':'alan','age':16,'marks':39},
           {'id':103,'Name':'jessy','age':17,'marks':44},
           {'id':104,'Name':'kate','age':18,'marks':45},
           {'id':105,'Name':'hardin','age':15,'marks':42}]
dataframe3=pd.DataFrame(list)
dataframe3

    id    Name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

In [101]:
dataframe3.age.max()#find max od list

18

In [102]:
dataframe3['age'].max()#another way to find max

18

In [103]:
dataframe3['age'].min()

15

In [104]:
dataframe3.age.min()

15

In [105]:
dataframe3.marks.mean()

43.8

In [106]:
dataframe3.age.std()

1.3038404810405297

In [111]:
#to get statistical summary of the data 
dataframe3.describe()

               id       age      marks
count    5.000000   5.00000   5.000000
mean   103.000000  16.20000  43.800000
std      1.581139   1.30384   3.701351
min    101.000000  15.00000  39.000000
25%    102.000000  15.00000  42.000000
50%    103.000000  16.00000  44.000000
75%    104.000000  17.00000  45.000000
max    105.000000  18.00000  49.000000

CONDITIONAL SELECTING:

In [114]:
list=[{'id':101,'Name':'sam','age':15,'marks':49},
           {'id':102,'Name':'alan','age':16,'marks':39},
           {'id':103,'Name':'jessy','age':17,'marks':44},
           {'id':104,'Name':'kate','age':18,'marks':45},
           {'id':105,'Name':'hardin','age':15,'marks':42}]
dataframe3=pd.DataFrame(list)
dataframe3

    id    Name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

In [116]:
df[df['age']>16]#get the values baove age 25

    Id   Name  age  marks
2  103  jessy   17     44
3  104   kate   18     45

In [ ]:
df['Name'][df.marks==df.marks.min()]#min salary with name

1    alan
Name: Name, dtype: object

HANDLING MISSING DATA

In [119]:
data_missing=pd.read_csv('C:\\Users\\pc\\python-basics\\weather_data_missing_pandas.csv')
data_missing

           day     city  temperature  windspeed   event
0   01-01-2017  newyork         32.0          6    Rain
1   01-02-2017  newyork          NaN          7   Sunny
2   01-02-2017  newyork         28.0      99999    Snow
3   01-02-2017  newyork         33.0          7   Sunny
4   01-02-2017   mumbai         90.0          5       0
5   01-02-2017   mumbai         85.0         12     Fog
6   01-02-2017   mumbai         87.0         15     Fog
7   01-02-2017   mumbai          NaN          5    Rain
8   01-02-2017    paris         45.0         20   Sunny
9   01-02-2017    paris         50.0      -1111  Cloudy
10  01-02-2017    paris         54.0          8  Cloudy
11  01-02-2017    paris         42.0         10  Cloudy

In [ ]:
#checking missing values :
data_missing.isna()#or isnull()

      day   city  temperature  windspeed  event
0   False  False        False      False  False
1   False  False         True      False  False
2   False  False        False      False  False
3   False  False        False      False  False
4   False  False        False      False  False
5   False  False        False      False  False
6   False  False        False      False  False
7   False  False         True      False  False
8   False  False        False      False  False
9   False  False        False      False  False
10  False  False        False      False  False
11  False  False        False      False  False

In [122]:
data_missing.isna().sum()#sum of missing values

day            0
city           0
temperature    2
windspeed      0
event          0
dtype: int64

In [123]:
data_missing.isnull().sum()

day            0
city           0
temperature    2
windspeed      0
event          0
dtype: int64

In [ ]:
#filling missing values:
data2=data_missing.fillna(0)#fills 0 in null value 
data2

           day     city  temperature  windspeed   event
0   01-01-2017  newyork         32.0          6    Rain
1   01-02-2017  newyork          0.0          7   Sunny
2   01-02-2017  newyork         28.0      99999    Snow
3   01-02-2017  newyork         33.0          7   Sunny
4   01-02-2017   mumbai         90.0          5       0
5   01-02-2017   mumbai         85.0         12     Fog
6   01-02-2017   mumbai         87.0         15     Fog
7   01-02-2017   mumbai          0.0          5    Rain
8   01-02-2017    paris         45.0         20   Sunny
9   01-02-2017    paris         50.0      -1111  Cloudy
10  01-02-2017    paris         54.0          8  Cloudy
11  01-02-2017    paris         42.0         10  Cloudy

In [ ]:
avg=data_missing['temperature'].mean()
data_missing.fillna(avg)#mising data in temp will replace with avrg of temp

           day     city  temperature  windspeed   event
0   01-01-2017  newyork         32.0          6    Rain
1   01-02-2017  newyork         54.6          7   Sunny
2   01-02-2017  newyork         28.0      99999    Snow
3   01-02-2017  newyork         33.0          7   Sunny
4   01-02-2017   mumbai         90.0          5       0
5   01-02-2017   mumbai         85.0         12     Fog
6   01-02-2017   mumbai         87.0         15     Fog
7   01-02-2017   mumbai         54.6          5    Rain
8   01-02-2017    paris         45.0         20   Sunny
9   01-02-2017    paris         50.0      -1111  Cloudy
10  01-02-2017    paris         54.0          8  Cloudy
11  01-02-2017    paris         42.0         10  Cloudy

In [ ]:
data_missing.fillna(method='ffill')#forward fill
#data_missing.ffill()(mising values wil get the value above it)

C:\Users\pc\AppData\Local\Temp\ipykernel_7356\782348161.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_missing.fillna(method='ffill')#forward fill

           day     city  temperature  windspeed   event
0   01-01-2017  newyork         32.0          6    Rain
1   01-02-2017  newyork         32.0          7   Sunny
2   01-02-2017  newyork         28.0      99999    Snow
3   01-02-2017  newyork         33.0          7   Sunny
4   01-02-2017   mumbai         90.0          5       0
5   01-02-2017   mumbai         85.0         12     Fog
6   01-02-2017   mumbai         87.0         15     Fog
7   01-02-2017   mumbai         87.0          5    Rain
8   01-02-2017    paris         45.0         20   Sunny
9   01-02-2017    paris         50.0      -1111  Cloudy
10  01-02-2017    paris         54.0          8  Cloudy
11  01-02-2017    paris         42.0         10  Cloudy

In [127]:
data_missing.fillna(method='bfill')#backward fill
#data-missing.bfill()

C:\Users\pc\AppData\Local\Temp\ipykernel_7356\1231838561.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_missing.fillna(method='bfill')#backward fill

           day     city  temperature  windspeed   event
0   01-01-2017  newyork         32.0          6    Rain
1   01-02-2017  newyork         28.0          7   Sunny
2   01-02-2017  newyork         28.0      99999    Snow
3   01-02-2017  newyork         33.0          7   Sunny
4   01-02-2017   mumbai         90.0          5       0
5   01-02-2017   mumbai         85.0         12     Fog
6   01-02-2017   mumbai         87.0         15     Fog
7   01-02-2017   mumbai         45.0          5    Rain
8   01-02-2017    paris         45.0         20   Sunny
9   01-02-2017    paris         50.0      -1111  Cloudy
10  01-02-2017    paris         54.0          8  Cloudy
11  01-02-2017    paris         42.0         10  Cloudy

LINEAR INTERPOLATION:

Linear interpolation is a technique used to estimate missing values 
in a dataframe or series by filling in the gaps with values that lie on the stright line between knwon data points 
specifically,you can use the interpolate ()method with the method ='linear'parameter
the method ='linear'is the default for the dataframes and it treats the index value as equally spaced

In [131]:
#creating datafrma ewith missing values:
import numpy as np
df=pd.DataFrame({'A':[1,2,np.nan,4],
              'B':[5,np.nan,np.nan,8],
              'C':[9,10,11,12]})

# applying linear interpolation
df_interpolated=df.interpolate(method='linear')
print(df_interpolated)

     A    B   C
0  1.0  5.0   9
1  2.0  6.0  10
2  3.0  7.0  11
3  4.0  8.0  12

In [132]:
data_missing.interpolate()#linear interpoaltion dills with average of preceeding and after eleemnt

C:\Users\pc\AppData\Local\Temp\ipykernel_7356\1387875951.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  data_missing.interpolate()#linear interpoaltion dills with average of preceeding and after eleemnt

           day     city  temperature  windspeed   event
0   01-01-2017  newyork         32.0          6    Rain
1   01-02-2017  newyork         30.0          7   Sunny
2   01-02-2017  newyork         28.0      99999    Snow
3   01-02-2017  newyork         33.0          7   Sunny
4   01-02-2017   mumbai         90.0          5       0
5   01-02-2017   mumbai         85.0         12     Fog
6   01-02-2017   mumbai         87.0         15     Fog
7   01-02-2017   mumbai         66.0          5    Rain
8   01-02-2017    paris         45.0         20   Sunny
9   01-02-2017    paris         50.0      -1111  Cloudy
10  01-02-2017    paris         54.0          8  Cloudy
11  01-02-2017    paris         42.0         10  Cloudy

In [133]:
data_missing.dropna()#drop rows with null values

           day     city  temperature  windspeed   event
0   01-01-2017  newyork         32.0          6    Rain
2   01-02-2017  newyork         28.0      99999    Snow
3   01-02-2017  newyork         33.0          7   Sunny
4   01-02-2017   mumbai         90.0          5       0
5   01-02-2017   mumbai         85.0         12     Fog
6   01-02-2017   mumbai         87.0         15     Fog
8   01-02-2017    paris         45.0         20   Sunny
9   01-02-2017    paris         50.0      -1111  Cloudy
10  01-02-2017    paris         54.0          8  Cloudy
11  01-02-2017    paris         42.0         10  Cloudy

In [134]:
#drop rows with full NaN values in other words,if a row has any nan value ,it wont be deleted 
data_missing.dropna(how='all')

           day     city  temperature  windspeed   event
0   01-01-2017  newyork         32.0          6    Rain
1   01-02-2017  newyork          NaN          7   Sunny
2   01-02-2017  newyork         28.0      99999    Snow
3   01-02-2017  newyork         33.0          7   Sunny
4   01-02-2017   mumbai         90.0          5       0
5   01-02-2017   mumbai         85.0         12     Fog
6   01-02-2017   mumbai         87.0         15     Fog
7   01-02-2017   mumbai          NaN          5    Rain
8   01-02-2017    paris         45.0         20   Sunny
9   01-02-2017    paris         50.0      -1111  Cloudy
10  01-02-2017    paris         54.0          8  Cloudy
11  01-02-2017    paris         42.0         10  Cloudy

In [135]:
#any drop rows with any of the value is nan
data_missing.dropna(how='any')

           day     city  temperature  windspeed   event
0   01-01-2017  newyork         32.0          6    Rain
2   01-02-2017  newyork         28.0      99999    Snow
3   01-02-2017  newyork         33.0          7   Sunny
4   01-02-2017   mumbai         90.0          5       0
5   01-02-2017   mumbai         85.0         12     Fog
6   01-02-2017   mumbai         87.0         15     Fog
8   01-02-2017    paris         45.0         20   Sunny
9   01-02-2017    paris         50.0      -1111  Cloudy
10  01-02-2017    paris         54.0          8  Cloudy
11  01-02-2017    paris         42.0         10  Cloudy