In [ ]:
#pip install pandas
#!pip install pandas(to install pandas)
import pandas as pd

In [ ]:
print(pd.__version__)#to check the version pandas

2.3.3

In [ ]:
import numpy as np

PANDAS SERIES:

In [ ]:
#series:homogeneous and one diamensional (same type of elemnts)
#dataframe:hetrogeneous and two diamensional(differnt)

In [9]:

series_data=np.array([1,2,3,4,5])
pd.Series(series_data)

0    1
1    2
2    3
3    4
4    5
dtype: int64

DATA FRAME USING PYTHON DICTIONARY:

In [15]:
data={'Id':[101,102,103,104,105],'Name':['sam','alan','jessy','kate','hardin'],
'age':[15,16,17,18,15],'marks':[49,39,44,45,42]}
data

{'Id': [101, 102, 103, 104, 105],
 'Name': ['sam', 'alan', 'jessy', 'kate', 'hardin'],
 'age': [15, 16, 17, 18, 15],
 'marks': [49, 39, 44, 45, 42]}

In [16]:
dataframe1=pd.DataFrame(data)
dataframe1

    Id    Name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

DATA TYPE USING PYTHON TUPLE LIST:

In [17]:
data_tup=[(101,"sam",15,49),
          (102,"alan",16,39),
          (103,"jessy",17,44),
          (104,"kate",18,45),
          (105,"hardin",15,42)]
dataframe=pd.DataFrame(data_tup,columns=['id','name','age','marks'])
dataframe

    id    name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

DATAFRAME USING LIST OF DICTIONARIES:

In [19]:
data_list=[{'id':101,'Name':'sam','age':15,'marks':49},
           {'id':102,'Name':'alan','age':16,'marks':39},
           {'id':103,'Name':'jessy','age':17,'marks':44},
           {'id':104,'Name':'kate','age':18,'marks':45},
           {'id':105,'Name':'hardin','age':15,'marks':42}]
dataframe3=pd.DataFrame(data_list)
dataframe3

    id    Name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

READING A CSV FILE:

In [23]:
data=pd.read_csv('C:\\Users\\pc3\\python-basics\\weather_data_pandas (5).csv')#comma seperated values
data

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  01-02-2017           35          7  Sunny
2  01-03-2017           28          2   Snow
3  01-04-2017           24          7   Snow
4  01-05-2017           32          4   Rain
5  01-06-2017           31          2  Sunny

SKIP UNNECESSERY HEADERS AND ADD NEW HEADERS WHILE READING A CSV FILE:

In [4]:

data=pd.read_csv('C:\\Users\\pc3\\python-basics\\stock_data_pandas.csv')
data

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3     RIL  not available       50  1023  mukesh ambani
4    TATA             -1       -1  n.a.     ratan tata

In [5]:
#SKIPROWS:-skip the specified number of rows from the begining including the header row
data1=pd.read_csv('C:\\Users\\pc3\\python-basics\\stock_data_pandas.csv',skiprows=2)
data1

    WMT           4.61  484    65           n.a.
0  MSFT             -1   85    64     bill gates
1   RIL  not available   50  1023  mukesh ambani
2  TATA             -1   -1  n.a.     ratan tata

In [ ]:
#set the specified rows as the header discarding the remaining row of the data frame:
data2=pd.read_csv('C:\\Users\\pc3\\python-basics\\stock_data_pandas.csv',header=3)# will ser row 3 as header
data2

   MSFT             -1  85    64     bill gates
0   RIL  not available  50  1023  mukesh ambani
1  TATA             -1  -1  n.a.     ratan tata

In [ ]:
#make the header a new record:
d=pd.read_csv('C:\\Users\\pc3\\python-basics\\stock_data_pandas.csv',header=None)#header will be shown as new row and by default index no will be given
d

         0              1        2      3              4
0  tickers            eps  revenue  price         people
1    GOOGL          27.82       87    845     larry page
2      WMT           4.61      484     65           n.a.
3     MSFT             -1       85     64     bill gates
4      RIL  not available       50   1023  mukesh ambani
5     TATA             -1       -1   n.a.     ratan tata

In [9]:
#sets new names for the column:
data3=pd.read_csv('C:\\Users\\pc3\\python-basics\\stock_data_pandas.csv',header=None,names=["a","b","c","d","e"])
data3

         a              b        c      d              e
0  tickers            eps  revenue  price         people
1    GOOGL          27.82       87    845     larry page
2      WMT           4.61      484     65           n.a.
3     MSFT             -1       85     64     bill gates
4      RIL  not available       50   1023  mukesh ambani
5     TATA             -1       -1   n.a.     ratan tata

In [ ]:
#select only the first nrows from the data frames:
data4=pd.read_csv('C:\\Users\\pc3\\python-basics\\stock_data_pandas.csv',nrows=3)
data4 #will show first 3 rows only

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.
2    MSFT  -1.00       85     64  bill gates

In [12]:
#sets specific values from the dataframesas nul values:
#NaN-not a number (missing values)
data5=pd.read_csv('C:\\Users\\pc3\\python-basics\\stock_data_pandas.csv',na_values=['n.a.','not available'])
data5

  tickers    eps  revenue   price         people
0   GOOGL  27.82       87   845.0     larry page
1     WMT   4.61      484    65.0            NaN
2    MSFT  -1.00       85    64.0     bill gates
3     RIL    NaN       50  1023.0  mukesh ambani
4    TATA  -1.00       -1     NaN     ratan tata

In [14]:
data6=pd.read_csv('C:\\Users\\pc3\\python-basics\\stock_data_pandas.csv',na_values={'eps':['not available',-1],
                                                                                    'revenue':['n.a. ',-1,"-1"],'price':['n.a.',-1],
                                                                                      'people':['n.a','not available',-1]})
data6

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0           n.a.
2    MSFT    NaN     85.0    64.0     bill gates
3     RIL    NaN     50.0  1023.0  mukesh ambani
4    TATA    NaN      NaN     NaN     ratan tata

BASIC

In [15]:
emp={'Id':[101,102,103,104,105],'Name':['sam','alan','jessy','kate','hardin'],
'age':[15,16,17,18,15],'marks':[49,39,44,45,42]}
df=pd.DataFrame(emp)
df

    Id    Name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

In [16]:
#get shape og the dataframe
df.shape

(5, 4)

In [17]:
#display the 5 rows of dataframe:
df.head()

    Id    Name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

In [18]:
#return the specific number of records from the begining:
df.head(3)

    Id   Name  age  marks
0  101    sam   15     49
1  102   alan   16     39
2  103  jessy   17     44

In [19]:
#return last 5 rows
df.tail()

    Id    Name  age  marks
0  101     sam   15     49
1  102    alan   16     39
2  103   jessy   17     44
3  104    kate   18     45
4  105  hardin   15     42

In [20]:
df.tail(2)

    Id    Name  age  marks
3  104    kate   18     45
4  105  hardin   15     42

In [21]:
#get the names of columns 
df.columns

Index(['Id', 'Name', 'age', 'marks'], dtype='object')

In [22]:
#accessing a specific column
df.age

0    15
1    16
2    17
3    18
4    15
Name: age, dtype: int64

In [23]:
df['age']

0    15
1    16
2    17
3    18
4    15
Name: age, dtype: int64

In [26]:
#accessing multiple column:
df[['Id','Name','age']]

    Id    Name  age
0  101     sam   15
1  102    alan   16
2  103   jessy   17
3  104    kate   18
4  105  hardin   15